default:
  image:
    name: ubuntu:latest
  before_script:
    - apt-get update -yq
    - DEBIAN_FRONTEND=noninteractive apt-get install -yq devscripts sudo

deb:
  stage: build
  tags:
    - docker
  script:
    - yes "" | ./utils/do_debian_package.sh --snapshot=stable --branch=1.36.1 --type=binary --interactive=no --dput=no --debbuild-extra=--no-sign || true
  artifacts:
    paths:
      - '*.deb'
    expire_in: 1 week
